### ISSUE TITLE
def allocate_absentee in VEST notebooks

### ISSUE THREAD

**Issue by rootsmusic** [nonpartisan-redistricting-datahub/pdv-resources#2]
@rdhlily  VEST's [readme.txt](https://dataverse.harvard.edu/file.xhtml?fileId=4575858&version=2.0) noted that their code modified the largest_remainder function in [Dr. Lackner's apportionment method](https://github.com/martinlackner/apportionment).  I'm unsure which method is used by your allocate_absentee function.  Is it different enough from VEST's to explain discrepancies in the resulting allocation?  Thanks.

**Comment by peter-redistricting-data-hub** [comment]
Yes, it's very similar to what VEST uses. Sometimes there are differences of plus or minus one from our code to VEST (because of how ties are being broken) but other than that, we consistently get their same results

**Comment by rootsmusic** [comment]
Thanks @peter-redistricting-data-hub, I thought I'd raise this issue because I'm assuming that ALARM also replicated the largest_remainder function in their code.

**Comment by rootsmusic** [comment]
@peter-redistricting-data-hub You've been editing functions in Notebook_Report_Guidelines.ipynb.  Some edits add comments, but they're still helpful in understanding complex functions.  When the older notebooks in the other repos are being revised, please also revise their functions.
