### ISSUE TITLE
functions for "checking shapefiles in progress"

### ISSUE THREAD

**Issue by rootsmusic** [nonpartisan-redistricting-datahub/pdv-resources#3]
Notebook_Report_Guidelines.ipynb says that development of its function for checking shapefiles is in progress.  Is that why nc_vest_2020.ipynb didn't run the last couple of cells?

If the function is still in progress, you may be interested in integrating your partner's [script to verify shapefiles](https://github.com/OpenPrecincts/verification).  Since shapefile_validater doesn't have any comments, I'm unsure what it's validating.  Can it validate which precinct shapes match which VTD shapes?  If it can't, do you know of a script that can?  Thanks.

**Comment by peter-redistricting-data-hub** [comment]
Good question. The "function" for checking shapefiles is still in progress, but the code that we use works, it just hasn't been combined into one Python function. If you take a look at the code blocks that start with "both = final_merge[final_merge["final_merge"]=="both"]", "count = 0", and "df = pd.DataFrame(area_list)" that's the code we've been using. I'm not sure what you mean on the last couple of cells not running, were you getting an error somewhere?

I'll take a look at the Open Elections precinct verification code, thanks for passing along!

**Comment by rootsmusic** [comment]
You're welcome, @peter-redistricting-data-hub.  Can your function validate which precinct shapes match which VTD shapes? If it can't, then do you know of a script that can?  Thanks.

P.S. [nc_vest_2020.ipynb](https://github.com/nonpartisan-redistricting-datahub/pdv-nc/blob/main/vest-nc-2020/nc_vest_2020.ipynb) didn't run the last couple of cells, which I assume that David is waiting for revised code.

**Comment by peter-redistricting-data-hub** [comment]
If you have a dataframe where precincts are joined to VTDs (so in every row there would be a precinct and the VTD it likely matches with), the code we have can tell you how much it overlaps or where it differs. If you'd like to figure out which VTD matches best with what precinct (so you don't have names or anything to join off of) we'd have to write a new function for that.

And weird on the code at the end not running, it runs fully on my machine.
